Repository MCF-x-Course-Hero/pomodoro-timer, pull requests merged in 2022-07, with the labels that each got.

#35 Adding Tasks on Sidebar
  react-app/pomodoro-timer-ui/package-lock.json
  react-app/pomodoro-timer-ui/package.json
  react-app/pomodoro-timer-ui/src/Components/App/App.jsx
  react-app/pomodoro-timer-ui/src/Components/BottomSidebar/BottomSidebar.css
  react-app/pomodoro-timer-ui/src/Components/BottomSidebar/BottomSidebar.jsx
  react-app/pomodoro-timer-ui/src/Components/ListTab/ListTab.css
  react-app/pomodoro-timer-ui/src/Components/ListTab/ListTab.jsx
  react-app/pomodoro-timer-ui/src/Components/TodoTab/Todo.jsx
  react-app/pomodoro-timer-ui/src/Components/TodoTab/TodoForm.jsx
  react-app/pomodoro-timer-ui/src/Components/TodoTab/TodoList.jsx
  react-app/pomodoro-timer-ui/src/Components/TodoTab/TodoTab.css
  react-app/pomodoro-timer-ui/src/Components/TodoTab/TodoTab.jsx
  react-app/pomodoro-timer-ui/src/Components/TopSidebar/TopSidebar.css
  react-app/pomodoro-timer-ui/src/contexts/TodoContext.jsx
Labels: Front End

#37 User Login and Register
  react-app/pomodoro-timer-api/routes/auth.js
  react-app/pomodoro-timer-ui/package-lock.json
  react-app/pomodoro-timer-ui/package.json
  react-app/pomodoro-timer-ui/src/Components/App/App.jsx
  react-app/pomodoro-timer-ui/src/Components/LoginForm/LoginForm.css
  react-app/pomodoro-timer-ui/src/Components/LoginForm/LoginForm.jsx
  react-app/pomodoro-timer-ui/src/Components/ProfileTab/ProfileTab.css
  react-app/pomodoro-timer-ui/src/Components/RegisterFrom/RegisterForm.css
  react-app/pomodoro-timer-ui/src/Components/RegisterFrom/RegisterForm.jsx
  react-app/pomodoro-timer-ui/src/Components/SettingsTab/SettingsTab.jsx
  react-app/pomodoro-timer-ui/src/Components/TopSidebar/TopSidebar.css
  react-app/pomodoro-timer-ui/src/Components/TopSidebar/TopSidebar.jsx
  react-app/pomodoro-timer-ui/src/Services/apiClient.js
  react-app/pomodoro-timer-ui/src/contexts/auth.jsx
  react-app/pomodoro-timer-ui/src/main.jsx
Labels: Front End, Back End

#38 Settings
  react-app/.vscode/settings.json
  react-app/pomodoro-timer-ui/.gitignore
  react-app/pomodoro-timer-ui/package-lock.json
  react-app/pomodoro-timer-ui/package.json
  react-app/pomodoro-timer-ui/public/vite.svg
  react-app/pomodoro-timer-ui/src/Components/App/App.css
  react-app/pomodoro-timer-ui/src/Components/App/App.jsx
  react-app/pomodoro-timer-ui/src/Components/BottomSidebar/BottomSidebar.css
  react-app/pomodoro-timer-ui/src/Components/BottomSidebar/BottomSidebar.jsx
  react-app/pomodoro-timer-ui/src/Components/SettingsTab/SettingsTab.css
  react-app/pomodoro-timer-ui/src/Components/SettingsTab/SettingsTab.jsx
  react-app/pomodoro-timer-ui/src/Components/Sidebar/Sidebar.css
  react-app/pomodoro-timer-ui/src/Components/Timer/Timer.css
  react-app/pomodoro-timer-ui/src/Components/Timer/Timer.jsx
  react-app/pomodoro-timer-ui/src/Components/TopSidebar/TopSidebar.css
  react-app/pomodoro-timer-ui/src/Components/TopSidebar/TopSidebar.jsx
  react-app/pomodoro-timer-ui/src/assets/bike-notif.wav
  react-app/pomodoro-timer-ui/src/assets/dark-forward.svg
  react-app/pomodoro-timer-ui/src/assets/dark-history.svg
  react-app/pomodoro-timer-ui/src/assets/dark-list.svg
  react-app/pomodoro-timer-ui/src/assets/dark-pause.svg
  react-app/pomodoro-timer-ui/src/assets/dark-play.svg
  react-app/pomodoro-timer-ui/src/assets/dark-profile.svg
  react-app/pomodoro-timer-ui/src/assets/dark-restart.svg
  react-app/pomodoro-timer-ui/src/assets/dark-settings.svg
  react-app/pomodoro-timer-ui/src/assets/soft-notif.mp3
  react-app/pomodoro-timer-ui/src/contexts/SettingsContext.jsx
  react-app/pomodoro-timer-ui/src/contexts/SidebarContext.jsx
  react-app/pomodoro-timer-ui/src/main.jsx
Labels: Front End

#39 Pin task
  react-app/pomodoro-timer-ui/src/Components/App/App.jsx
  react-app/pomodoro-timer-ui/src/Components/PinnedTodo/PinnedTodo.css
  react-app/pomodoro-timer-ui/src/Components/PinnedTodo/PinnedTodo.jsx
  react-app/pomodoro-timer-ui/src/Components/TodoTab/Todo.jsx
  react-app/pomodoro-timer-ui/src/Components/TodoTab/TodoForm.jsx
  react-app/pomodoro-timer-ui/src/Components/TodoTab/TodoTab.css
  react-app/pomodoro-timer-ui/src/Components/TodoTab/TodoTab.jsx
  react-app/pomodoro-timer-ui/src/contexts/TodoContext.jsx
Labels: Front End

#52 Tasks models
  package-lock.json
  react-app/pomodoro-timer-api/models/task.js
  react-app/pomodoro-timer-api/routes/task.js
Labels: Back End
